tags:
  - name: Accounts
    description: Accounts and Sessions related operations
  - name: Profiles
    description: Profiles related operations
  - name: Tags
    description: Tags and Tag Categories related operations
  - name: Projects
    description: Projects and Files related operations
components:
  schemas:
    Expense:
      type: object
      required:
        - id
        - name
        - owner_id
        - amount
        - max_yearly_growth_rate
        - min_yearly_growth_rate
        - start_age
        - created_at
      properties:
        id:
          type: integer
          format: int32
          description: "Primary key of the expense"
          example: 1
        name:
          type: string
          maxLength: 64
          description: "Name of the expense"
          example: "Living Cost per year"
        owner_id:
          type: integer
          format: int32
          description: "Foreign key referencing the owner"
          example: 101
        amount:
          type: integer
          format: int32
          description: "The expense amount in New Taiwan Dollar (NTD)"
          example: 150000
        description:
          type: string
          description: "Detailed description of the expense"
          nullable: true
          example: "Living cost in Taipei for a year"
        max_yearly_growth_rate:
          type: number
          format: float
          description: "Maximum growing rate for the expense per year"
          example: 1.5
        min_yearly_growth_rate:
          type: number
          format: float
          description: "Minimum growing rate for the expense per year"
          example: 0.9
        start_age:
          type: integer
          format: int16
          description: "The starting age when this expense applies"
          example: 25
        end_age:
          type: integer
          format: int16
          description: "The ending age when this expense applies, null if indefinite"
          nullable: true
          example: 65
        created_at:
          type: string
          format: date
          description: "Date when the expense record was created"
          example: "2025-02-26"
    Income:
      type: object
      required:
        - id
        - name
        - owner_id
        - amount
        - max_yearly_growth_rate
        - min_yearly_growth_rate
        - start_age
        - created_at
      properties:
        id:
          type: integer
          format: int32
          description: "Primary key of the income"
          example: 1
        name:
          type: string
          maxLength: 64
          description: "Name of the income"
          example: "Salary per year"
        owner_id:
          type: integer
          format: int32
          description: "Foreign key referencing the owner"
          example: 101
        amount:
          type: integer
          format: int32
          description: "The income amount in New Taiwan Dollar (NTD)"
          example: 1000000
        description:
          type: string
          description: "Detailed description of the income"
          nullable: true
          example: "Salary as a SWE in Taipei for a year"
        max_yearly_growth_rate:
          type: number
          format: float
          description: "Maximum growing rate for the income per year"
          example: 1.5
        min_yearly_growth_rate:
          type: number
          format: float
          description: "Minimum growing rate for the income per year"
          example: 0.9
        start_age:
          type: integer
          format: int16
          description: "The starting age when this income applies"
          example: 25
        end_age:
          type: integer
          format: int16
          description: "The ending age when this income applies, null if indefinite"
          nullable: true
          example: 65
        created_at:
          type: string
          format: date
          description: "Date when the income record was created"
          example: "2025-02-26"
    Asset:
      type: object
      required:
        - id
        - name
        - owner_id
        - amount
        - max_yearly_return_rate
        - min_yearly_return_rate
        - start_age
        - created_at
      properties:
        id:
          type: integer
          format: int32
          description: "Primary key of the asset"
          example: 1
        name:
          type: string
          maxLength: 64
          description: "Name of the asset"
          example: "TSMC Stock Holding"
        owner_id:
          type: integer
          format: int32
          description: "Foreign key referencing the owner"
          example: 101
        amount:
          type: integer
          format: int32
          description: "The asset amount in New Taiwan Dollar (NTD)"
          example: 300000
        description:
          type: string
          description: "Detailed description of the asset"
          nullable: true
          example: "TSMC Stock Holding"
        max_yearly_return_rate:
          type: number
          format: float
          description: "Maximum return rate for the asset per year"
          example: 10
        min_yearly_return_rate:
          type: number
          format: float
          description: "Minimum return rate for the asset per year"
          example: -5
        start_age:
          type: integer
          format: int16
          description: "The starting age when this asset applies"
          example: 25
        end_age:
          type: integer
          format: int16
          description: "The ending age when this asset applies, null if indefinite"
          nullable: true
          example: 65
        created_at:
          type: string
          format: date
          description: "Date when the asset record was created"
          example: "2025-02-26"
    House:
      type: object
      required:
        - id
        - name
        - owner_id
        - amount
        - down_payment
        - interest_rate
        - loan_term
        - purchase_age
        - created_at
      properties:
        id:
          type: integer
          format: int32
          description: "Primary key of the house"
          example: 1
        name:
          type: string
          maxLength: 64
          description: "Name of the house"
          example: "Mandakini A"
        owner_id:
          type: integer
          format: int32
          description: "Foreign key referencing the owner"
          example: 101
        amount:
          type: number
          format: double
          description: "The house amount in New Taiwan Dollar (NTD)"
          example: 50000000
        down_payment:
          type: number
          format: double
          description: "Initial payment made towards the house purchase"
          example: 15000000
        interest_rate:
          type: number
          format: float
          description: "Annual interest rate for the mortgage"
          example: 0.035
        loan_term:
          type: integer
          format: int16
          description: "Loan term duration in years"
          example: 40
        description:
          type: string
          nullable: true
          description: "Detailed description of the house"
          example: "Mandakini A, A good place for internation bro"
        purchase_age:
          type: integer
          format: int16
          description: "Age of the owner at the time of house purchase"
          example: 26
        sale_age:
          type: integer
          format: int16
          nullable: true
          description: "Age of the owner at the time of house sale (null if not sold)"
          example: 65
        created_at:
          type: string
          format: date-time
          description: "Timestamp when the house record was created"
          example: "2025-02-26"
    Child:
      type: object
      required:
        - id
        - name
        - parent_id
        - birth_age
        - created_at
      properties:
        id:
          type: integer
          format: int32
          description: "Primary key of the child"
          example: 1
        name:
          type: string
          maxLength: 64
          description: "Name of the child"
          example: "Tang Juan"
        parent_id:
          type: integer
          format: int32
          description: "Foreign key referencing the parent. (record owner)"
          example: 101
        description:
          type: string
          description: "Detailed description of the child"
          nullable: true
          example: "Tang Juan is a lovely kid."
        birth_age:
          type: integer
          format: int16
          description: "The age of the parent when the child was born."
          example: 30
        independent_age:
          type: integer
          format: int16
          nullable: true
          description: "The estimated age when the child becomes financially independent."
        created_at:
          type: string
          format: date
          description: "Date when the child record was created"
          example: "2025-02-26"
    Liability:
      type: object
      required:
        - id
        - name
        - owner_id
        - principal_amount
        - interest_rate
        - start_age
        - end_age
        - created_at
      properties:
        id:
          type: integer
          format: int32
          description: "Primary key of the liability"
          example: 1
        name:
          type: string
          maxLength: 64
          description: "Name of the liability"
          example: "Student Loan"
        owner_id:
          type: integer
          format: int32
          description: "Foreign key referencing the owner"
          example: 101
        description:
          type: string
          nullable: true
          description: "Detailed description of the liability"
          example: "Toyota Altis"
        principal_amount:
          type: number
          format: float
          description: "Initial borrowed amount or principal liability"
          example: 900000
        interest_rate:
          type: number
          format: float
          description: "Annual interest rate percentage"
          example: 0.05
        start_age:
          type: integer
          format: int16
          description: "The starting age when this liability applies"
          example: 25
        end_age:
          type: integer
          format: int16
          description: "The ending age when this liability applies"
          example: 40
        created_at:
          type: string
          format: date
          description: "Timestamp when the record was created"
          example: "2025-02-26"
    Risk:
      type: object
      required:
        - id
        - name
        - owner_id
        - max_loss
        - min_loss
        - start_age
        - created_at
      properties:
        id:
          type: integer
          format: int32
          description: "Primary key of the risk"
          example: 1
        name:
          type: string
          maxLength: 64
          description: "Name of the asset"
          example: "General Daily Risk"
        owner_id:
          type: integer
          format: int32
          description: "Foreign key referencing the owner"
          example: 101
        max_loss:
          type: number
          format: float
          description: "Maximum possible loss due to the risk"
        min_loss:
          type: number
          format: float
          description: "Minimum possible loss due to the risk"
        description:
          type: string
          description: "Detailed description of the risk"
          nullable: true
          example: "General Daily Risk, like losing or breaking things, or getting colds"
        start_age:
          type: integer
          format: int16
          description: "The starting age when this risk applies"
          example: 25
        end_age:
          type: integer
          format: int16
          nullable: true
          description: "The ending age when this risk applies, null if indefinite"
          example: 65
        created_at:
          type: string
          format: date
          description: "Date when the risk record was created"
          example: "2025-02-26"
    # Account:
    #   type: object
    #   properties:
    #     id:
    #       type: string
    #       readOnly: true 
    #     email:
    #       type: string
    #       format: email
    #     created_time:
    #       type: string
    #       format: date-time 
    #       writeOnly: true  
    #     password:
    #       type: string
    #       format: password 
    #       minLength: 8
    #       writeOnly: true 
    # Profile:
    #   type: object
    #   properties:
    #     id:
    #       type: string
    #       readOnly: true 
    #     name:
    #       type: string
    #       minLength: 2 
    #       maxLength: 50
    #     description:
    #       type: string
    #     updated_time:
    #       type: string
    #       format: date-time 
    #       writeOnly: true
    #     profile_photo:
    #       type: string
    # Tag:
    #   type: object
    #   properties:
    #     id:
    #       type: string
    #       readOnly: true 
    #     tag_category_id:
    #       type: string
    #       readOnly: true
    #     name:
    #       type: string
    #       minLength: 2 
    #       maxLength: 50
    # TagCategory:
    #   type: object
    #   properties:
    #     id:
    #       type: string
    #       readOnly: true
    #     name:
    #       type: string
    #       minLength: 2 
    #       maxLength: 50
    #     color:
    #       type: string
    # File:
    #   type: object
    #   properties:
    #     id:
    #       type: string
    #       readOnly: true
    #     project_id:
    #       type: string
    #       readOnly: true
    #     name:
    #       type: string
    #       minLength: 2 
    #       maxLength: 50
    #     reference:
    #       type: string
    #     uploaded_time:
    #       type: string
    #       format: date-time 
    #       writeOnly: true
    # Project:
    #   type: object
    #   properties:
    #     id:
    #       type: string
    #       readOnly: true
    #     account_id:
    #       type: string
    #       readOnly: true
    #     share:
    #       type: string
    #       enum:
    #         - public
    #         - private
    #     name:
    #       type: string
    #       minLength: 2 
    #       maxLength: 50
    #     like_number:
    #       type: integer
    #       minLength: 0
    #     watch_number:
    #       type: integer
    #       minLength: 0
    #     bookmark_number:
    #       type: integer
    #       minLength: 0
    #     from_date:
    #       type: string
    #       format: date
    #     to_date:
    #       type: string
    #       format: date
    #     team_size:
    #       type: integer
    #       minLength: 0
    #     summary:
    #       type: string
    #     created_time:
    #       type: string
    #       format: date-time 
    #       writeOnly: true
    #     photo:
    #       type: string
    # Session:
    #   type: object
    #   properties:
    #     user_id:
    #       type: string
    #     auth_header:
    #       type: string
    # # Source: https://github.com/designapis/openapi/blob/main/ch20/openapi.yml
    # OASError: 
    #   type: object
    #   properties:
    #     message:
    #       type: string
    #       description: Human-readable error message
    #     errors:
    #       type: array
    #       items:
    #         type: object
    #         properties:
    #           path:
    #             type: string
    #             description: For input validation errors, identifies where in the JSON request body the error occured
    #           message:
    #             type: string
    #             description: Human-readable error message
    #           errorCode:
    #             type: string
    #             description: Code indicating error type
    # Problem: 
    #   type: object
    #   properties:
    #     type:
    #       type: string
    #       description: URI indicating error type
    #     title:
    #       type: string
    #       description: Human-readable error title
    #     status:
    #       type: integer
    #       description: HTTP status code
    #     detail:
    #       type: string
    #       description: Human-readable error details
    #     instance:
    #       type: string
    #       description: URI indicating error instance
  securitySchemes:
    SessionToken:
      type: apiKey
      in: header
      name: Authorization
security:
  - SessionToken: []