openapi: 3.0.3
info:
  title: Tang Juan API
  version: 0.1.0
  description: |-

    This is the API documentation for the Tang Juan API.
    ---

    # Auth
    To get a **SecurityToken**:
    1. Create a **Account** with `POST /accounts/registration``
    2. Get a **SecurityToken** by calling `POST /sessions`` with your **Account** credentials.

  contact:
    name: Tang Juan API Support Team
    email: river1440@gmail.com

security:
  - apiKey: []
  - accessToken: []

tags:
  - name: Accounts
    description: "User accounts and registration"
  - name: Sessions
    description: "For Authentication"
  - name: Scenarios
    description: "Scenarios for finance simulation"
  - name: Expenses
    description: "Money spend in a year"
  - name: Incomes
    description: "Money earned in a year"
  - name: Assets
    description: "Capital which could be sold"
  - name: Liabilities
    description: "Capital which have to pay for"
  - name: Houses
    description: "House loan (mortgage)"
  - name: Children
    description: "Fee for raising children"
  - name: Risks
    description: "Risk as costing extra money"
  - name: Plots
    description: "For plotting resources"
servers:
  - url: https://njfps-backend-api.onrender.com
paths:
  /accounts/registration:
    $ref: "./paths/accounts.yml#/~1accounts~1registration"
  /accounts/registration/{token}:
    $ref: "./paths/accounts.yml#/~1accounts~1registration~1{token}"
  /sessions:
    $ref: "./paths/sessions.yml#/~1sessions"
  /sessions/access-tokens:
    $ref: "./paths/sessions.yml#/~1sessions~1access-tokens"
  /sessions/refresh-tokens:
    $ref: "./paths/sessions.yml#/~1sessions~1refresh-tokens"
  /accounts/{account_id}:
    $ref: "./paths/accounts.yml#/~1accounts~1{account_id}"
  /scenarios:
    $ref: "./paths/scenarios.yml#/~1scenarios"
  /scenarios/{scenario_id}:
    $ref: "./paths/scenarios.yml#/~1scenarios~1{scenario_id}"
  /expenses:
    $ref: "./paths/expenses.yml#/~1expenses"
  /expenses/{expense_id}:
    $ref: "./paths/expenses.yml#/~1expenses~1{expense_id}"
  /incomes:
    $ref: "./paths/incomes.yml#/~1incomes"
  /incomes/{income_id}:
    $ref: "./paths/incomes.yml#/~1incomes~1{income_id}"
  /assets:
    $ref: "./paths/assets.yml#/~1assets"
  /assets/{asset_id}:
    $ref: "./paths/assets.yml#/~1assets~1{asset_id}"
  /liabilities:
    $ref: "./paths/liabilities.yml#/~1liabilities"
  /liabilities/{liability_id}:
    $ref: "./paths/liabilities.yml#/~1liabilities~1{liability_id}"
  /houses:
    $ref: "./paths/houses.yml#/~1houses"
  /houses/{house_id}:
    $ref: "./paths/houses.yml#/~1houses~1{house_id}"
  /children:
    $ref: "./paths/children.yml#/~1children"
  /children/{child_id}:
    $ref: "./paths/children.yml#/~1children~1{child_id}"
  /risks:
    $ref: "./paths/risks.yml#/~1risks"
  /risks/{risk_id}:
    $ref: "./paths/risks.yml#/~1risks~1{risk_id}"
  /scenarios/{scenario_id}/expenses:
    $ref: "./paths/scenarios/expenses.yml#/~1scenarios~1{scenario_id}~1expenses"
  /scenarios/{scenario_id}/incomes:
    $ref: "./paths/scenarios/incomes.yml#/~1scenarios~1{scenario_id}~1incomes"
  /scenarios/{scenario_id}/assets:
    $ref: "./paths/scenarios/assets.yml#/~1scenarios~1{scenario_id}~1assets"
  /scenarios/{scenario_id}/liabilities:
    $ref: "./paths/scenarios/liabilities.yml#/~1scenarios~1{scenario_id}~1liabilities"
  /scenarios/{scenario_id}/houses:
    $ref: "./paths/scenarios/houses.yml#/~1scenarios~1{scenario_id}~1houses"
  /scenarios/{scenario_id}/children:
    $ref: "./paths/scenarios/children.yml#/~1scenarios~1{scenario_id}~1children"
  /scenarios/{scenario_id}/risks:
    $ref: "./paths/scenarios/risks.yml#/~1scenarios~1{scenario_id}~1risks"
  /scenarios/{scenario_id}/expenses/{expense_id}:
    $ref: "./paths/scenarios/expenses.yml#/~1scenarios~1{scenario_id}~1expenses~1{expense_id}"
  /scenarios/{scenario_id}/incomes/{income_id}:
    $ref: "./paths/scenarios/incomes.yml#/~1scenarios~1{scenario_id}~1incomes~1{income_id}"
  /scenarios/{scenario_id}/assets/{asset_id}:
    $ref: "./paths/scenarios/assets.yml#/~1scenarios~1{scenario_id}~1assets~1{asset_id}"
  /scenarios/{scenario_id}/liabilities/{liability_id}:
    $ref: "./paths/scenarios/liabilities.yml#/~1scenarios~1{scenario_id}~1liabilities~1{liability_id}"
  /scenarios/{scenario_id}/houses/{house_id}:
    $ref: "./paths/scenarios/houses.yml#/~1scenarios~1{scenario_id}~1houses~1{house_id}"
  /scenarios/{scenario_id}/children/{child_id}:
    $ref: "./paths/scenarios/children.yml#/~1scenarios~1{scenario_id}~1children~1{child_id}"
  /scenarios/{scenario_id}/risks/{risk_id}:
    $ref: "./paths/scenarios/risks.yml#/~1scenarios~1{scenario_id}~1risks~1{risk_id}"
  /plots/expenses/{expense_id}:
    $ref: "./paths/plots.yml#/~1plots~1expenses~1{expense_id}"
  /plots/incomes/{income_id}:
    $ref: "./paths/plots.yml#/~1plots~1incomes~1{income_id}"
  /plots/assets/{asset_id}:
    $ref: "./paths/plots.yml#/~1plots~1assets~1{asset_id}"
  /plots/liabilities/{liability_id}:
    $ref: "./paths/plots.yml#/~1plots~1liabilities~1{liability_id}"
  /plots/houses/{house_id}:
    $ref: "./paths/plots.yml#/~1plots~1houses~1{house_id}"
  /plots/children/{child_id}:
    $ref: "./paths/plots.yml#/~1plots~1children~1{child_id}"
  /plots/risks/{risk_id}:
    $ref: "./paths/plots.yml#/~1plots~1risks~1{risk_id}"
  /plots/scenarios/{scenario_id}/expenses/{expense_id}:
    $ref: "./paths/plots/scenarios/expenses.yml#/~1plots~1scenarios~1{scenario_id}~1expenses~1{expense_id}"
  /plots/scenarios/{scenario_id}/incomes/{income_id}:
    $ref: "./paths/plots/scenarios/incomes.yml#/~1plots~1scenarios~1{scenario_id}~1incomes~1{income_id}"
  /plots/scenarios/{scenario_id}/assets/{asset_id}:
    $ref: "./paths/plots/scenarios/assets.yml#/~1plots~1scenarios~1{scenario_id}~1assets~1{asset_id}"
  /plots/scenarios/{scenario_id}/liabilities/{liability_id}:
    $ref: "./paths/plots/scenarios/liabilities.yml#/~1plots~1scenarios~1{scenario_id}~1liabilities~1{liability_id}"
  /plots/scenarios/{scenario_id}/houses/{house_id}:
    $ref: "./paths/plots/scenarios/houses.yml#/~1plots~1scenarios~1{scenario_id}~1houses~1{house_id}"
  /plots/scenarios/{scenario_id}/children/{child_id}:
    $ref: "./paths/plots/scenarios/children.yml#/~1plots~1scenarios~1{scenario_id}~1children~1{child_id}"
  /plots/scenarios/{scenario_id}/risks/{risk_id}:
    $ref: "./paths/plots/scenarios/risks.yml#/~1plots~1scenarios~1{scenario_id}~1risks~1{risk_id}"
  /plots/scenarios/{scenario_id}/expenses:
    $ref: "./paths/plots/scenarios/expenses.yml#/~1plots~1scenarios~1{scenario_id}~1expenses"
  /plots/scenarios/{scenario_id}/incomes:
    $ref: "./paths/plots/scenarios/incomes.yml#/~1plots~1scenarios~1{scenario_id}~1incomes"
  /plots/scenarios/{scenario_id}/assets:
    $ref: "./paths/plots/scenarios/assets.yml#/~1plots~1scenarios~1{scenario_id}~1assets"
  /plots/scenarios/{scenario_id}/liabilities:
    $ref: "./paths/plots/scenarios/liabilities.yml#/~1plots~1scenarios~1{scenario_id}~1liabilities"
  /plots/scenarios/{scenario_id}/houses:
    $ref: "./paths/plots/scenarios/houses.yml#/~1plots~1scenarios~1{scenario_id}~1houses"
  /plots/scenarios/{scenario_id}/children:
    $ref: "./paths/plots/scenarios/children.yml#/~1plots~1scenarios~1{scenario_id}~1children"
  /plots/scenarios/{scenario_id}/risks:
    $ref: "./paths/plots/scenarios/risks.yml#/~1plots~1scenarios~1{scenario_id}~1risks"
  /plots/scenarios/{scenario_id}/expenses/total:
    $ref: "./paths/plots/scenarios/expenses.yml#/~1plots~1scenarios~1{scenario_id}~1expenses~1total"
  /plots/scenarios/{scenario_id}/incomes/total:
    $ref: "./paths/plots/scenarios/incomes.yml#/~1plots~1scenarios~1{scenario_id}~1incomes~1total"
  /plots/scenarios/{scenario_id}/assets/total:
    $ref: "./paths/plots/scenarios/assets.yml#/~1plots~1scenarios~1{scenario_id}~1assets~1total"
  /plots/scenarios/{scenario_id}/liabilities/total:
    $ref: "./paths/plots/scenarios/liabilities.yml#/~1plots~1scenarios~1{scenario_id}~1liabilities~1total"
  /plots/scenarios/{scenario_id}/houses/total:
    $ref: "./paths/plots/scenarios/houses.yml#/~1plots~1scenarios~1{scenario_id}~1houses~1total"
  /plots/scenarios/{scenario_id}/children/total:
    $ref: "./paths/plots/scenarios/children.yml#/~1plots~1scenarios~1{scenario_id}~1children~1total"
  /plots/scenarios/{scenario_id}/risks/total:
    $ref: "./paths/plots/scenarios/risks.yml#/~1plots~1scenarios~1{scenario_id}~1risks~1total"
  /plots/scenarios/{scenario_id}/cashflow:
    $ref: "./paths/plots/scenarios/aggregates.yml#/~1plots~1scenarios~1{scenario_id}~1cashflow"
  /plots/scenarios/{scenario_id}/capital:
    $ref: "./paths/plots/scenarios/aggregates.yml#/~1plots~1scenarios~1{scenario_id}~1capital"
  /plots/scenarios/{scenario_id}/wealth:
    $ref: "./paths/plots/scenarios/aggregates.yml#/~1plots~1scenarios~1{scenario_id}~1wealth"
components:
  schemas:
    Account:
      $ref: "./schemas/resources.yml#/Account"
    Session:
      $ref: "./schemas/auth.yml#/Session"
    Expense:
      $ref: "./schemas/resources.yml#/Expense"
    Income:
      $ref: "./schemas/resources.yml#/Income"
    Asset:
      $ref: "./schemas/resources.yml#/Asset"
    House:
      $ref: "./schemas/resources.yml#/House"
    Child:
      $ref: "./schemas/resources.yml#/Child"
    Liability:
      $ref: "./schemas/resources.yml#/Liability"
    Risk:
      $ref: "./schemas/resources.yml#/Risk"
    Scenario:
      $ref: "./schemas/resources.yml#/Scenario"
    ResourceType:
      $ref: "./schemas/resources.yml#/ResourceType"
    ScenarioExpense:
      $ref: "./schemas/relationships.yml#/ScenarioExpense"
    ScenarioIncome:
      $ref: "./schemas/relationships.yml#/ScenarioIncome"
    ScenarioAsset:
      $ref: "./schemas/relationships.yml#/ScenarioAsset"
    ScenarioLiability:
      $ref: "./schemas/relationships.yml#/ScenarioLiability"
    ScenarioHouse:
      $ref: "./schemas/relationships.yml#/ScenarioHouse"
    ScenarioChild:
      $ref: "./schemas/relationships.yml#/ScenarioChild"
    ScenarioRisk:
      $ref: "./schemas/relationships.yml#/ScenarioRisk"
    PlotBase:
      $ref: "./schemas/plots.yml#/PlotBase"
    ResourcePlot:
      $ref: "./schemas/plots.yml#/ResourcePlot"
    ScenarioResourcePlot:
      $ref: "./schemas/plots.yml#/ScenarioResourcePlot"
    ScenarioResourcePlotList:
      $ref: "./schemas/plots.yml#/ScenarioResourcePlotList"
    ScenarioResourcePlotTotal:
      $ref: "./schemas/plots.yml#/ScenarioResourcePlotTotal"
    ScenarioAggregatePlot:
      $ref: "./schemas/plots.yml#/ScenarioAggregatePlot"
    OASError: 
      $ref: "./schemas/errors.yml#/OASError"
    Problem:
      $ref: "./schemas/errors.yml#/Problem"
  securitySchemes:
    apiKey:
      $ref: "security.yml#/apiKey"
    accessToken:
      $ref: "security.yml#/accessToken"
    refreshToken:
      $ref: "security.yml#/refreshToken"
# Source: https://github.com/designapis/openapi/blob/main/ch20/openapi.yml