openapi: 3.0.3
info:
  title: Tang Juan API
  version: 0.1.0
  description: |-

    This is the API documentation for the Tang Juan API.
    ---

    # Auth
    To get a **SecurityToken**:
    1. Create a **Account** with `POST /accounts/registration``
    2. Get a **SecurityToken** by calling `POST /sessions`` with your **Account** credentials.

  contact:
    name: Tang Juan API Support Team
    email: river1440@gmail.com

security:
  - apiKey: []
  - accessToken: []

tags:
  - name: Accounts
    description: "User accounts and registration"
  - name: Sessions
    description: "For Authentication"
  - name: Scenarios
    description: "Scenarios for finance simulation"
  - name: Expenses
    description: "Money spend in a year"
  - name: Incomes
    description: "Money earned in a year"
  - name: Assets
    description: "Capital which could be sold"
  - name: Liabilities
    description: "Capital which have to pay for"
  - name: Houses
    description: "House loan (mortgage)"
  - name: Children
    description: "Fee for raising children"
  - name: Risks
    description: "Risk as costing extra money"
  - name: Plots
    description: "For plotting resources"
servers:
  - url: https://njfps-backend-api.onrender.com
paths:
  /accounts/registration: 
    $ref: "./paths/accounts.yml#/~1accounts~1registration"
  /accounts/registration/{token}: 
    $ref: "./paths/accounts.yml#/~1accounts~1registration~1{token}"
  /accounts/{account_id}: 
    $ref: "./paths/accounts.yml#/~1accounts~1{account_id}"
  /sessions: 
    $ref: "./paths/sessions.yml"
  /scenarios: 
    $ref: "./paths/scenarios.yml"
  /expenses: 
    $ref: "./paths/expenses.yml"
  /incomes: 
    $ref: "./paths/incomes.yml"
  /assets: 
    $ref: "./paths/assets.yml"
  /liabilities: 
    $ref: "./paths/liabilities.yml"
  /houses: 
    $ref: "./paths/houses.yml"
  /children: 
    $ref: "./paths/children.yml"
  /risks: 
    $ref: "./paths/risks.yml"
  /plots: 
    $ref: "./paths/plots.yml"
components:
  schemas:
    Account:
      $ref: "./schemas/resources.yml#/Account"
    Session:
      $ref: "./schemas/auth.yml#/Session"
    Expense:
      $ref: "./schemas/resources.yml#/Expense"
    Income:
      $ref: "./schemas/resources.yml#/Income"
    Asset:
      $ref: "./schemas/resources.yml#/Asset"
    House:
      $ref: "./schemas/resources.yml#/House"
    Child:
      $ref: "./schemas/resources.yml#/Child"
    Liability:
      $ref: "./schemas/resources.yml#/Liability"
    Risk:
      $ref: "./schemas/resources.yml#/Risk"
    Scenario:
      $ref: "./schemas/resources.yml#/Scenario"
    ResourceType:
      $ref: "./schemas/resources.yml#/ResourceType"
    ScenarioExpense:
      $ref: "./schemas/relationships.yml#/ScenarioExpense"
    ScenarioIncome:
      $ref: "./schemas/relationships.yml#/ScenarioIncome"
    ScenarioAsset:
      $ref: "./schemas/relationships.yml#/ScenarioAsset"
    ScenarioLiability:
      $ref: "./schemas/relationships.yml#/ScenarioLiability"
    ScenarioHouse:
      $ref: "./schemas/relationships.yml#/ScenarioHouse"
    ScenarioChild:
      $ref: "./schemas/relationships.yml#/ScenarioChild"
    ScenarioRisk:
      $ref: "./schemas/relationships.yml#/ScenarioRisk"
    PlotBase:
      $ref: "./schemas/plots.yml#/PlotBase"
    ResourcePlot:
      $ref: "./schemas/plots.yml#/ResourcePlot"
    ScenarioResourcePlot:
      $ref: "./schemas/plots.yml#/ScenarioResourcePlot"
    ScenarioResourcePlotList:
      $ref: "./schemas/plots.yml#/ScenarioResourcePlotList"
    ScenarioResourcePlotTotal:
      $ref: "./schemas/plots.yml#/ScenarioResourcePlotTotal"
    ScenarioAggregatePlot:
      $ref: "./schemas/plots.yml#/ScenarioAggregatePlot"
    OASError: 
      $ref: "./schemas/errors.yml#/OASError"
    Problem:
      $ref: "./schemas/errors.yml#/Problem"
  securitySchemes:
    apiKey:
      $ref: "security.yml#/apiKey"
    accessToken:
      $ref: "security.yml#/accessToken"
    refreshToken:
      $ref: "security.yml#/refreshToken"
# Source: https://github.com/designapis/openapi/blob/main/ch20/openapi.yml