openapi: 3.0.3
info:
  title: Tang Juan API
  version: 0.1.0
  description: |-

    This is the API documentation for the Tang Juan API.
    ---

    # Auth
    To get a **SecurityToken**:
    1. Create a **Account** with `POST /accounts/registration``
    2. Get a **SecurityToken** by calling `POST /sessions`` with your **Account** credentials.

  contact:
    name: Tang Juan API Support Team
    email: river1440@gmail.com

security:
  - apiKey: []
  - accessToken: []

tags:
  - name: Accounts
    description: "User accounts and registration"
  - name: Sessions
    description: "For Authentication"
  - name: Scenarios
    description: "Scenarios for finance simulation"
  - name: Expenses
    description: "Money spend in a year"
  - name: Incomes
    description: "Money earned in a year"
  - name: Assets
    description: "Capital which could be sold"
  - name: Liabilities
    description: "Capital which have to pay for"
  - name: Houses
    description: "House loan (mortgage)"
  - name: Children
    description: "Fee for raising children"
  - name: Risks
    description: "Risk as costing extra money"
  - name: Plots
    description: "For plotting resources"
servers:
  - url: https://njfps-backend-api.onrender.com
paths:
  /accounts/registration: 
    $ref: "./paths/accounts.yml#/~1accounts~1registration"
  /accounts/registration/{token}: 
    $ref: "./paths/accounts.yml#/~1accounts~1registration~1{token}"
  /accounts/{account_id}: 
    $ref: "./paths/accounts.yml#/~1accounts~1{account_id}"
  /sessions: 
    $ref: "./paths/sessions.yml"
  /scenarios: 
    $ref: "./paths/scenarios.yml"
  /expenses: 
    $ref: "./paths/expenses.yml"
  /incomes: 
    $ref: "./paths/incomes.yml"
  /assets: 
    $ref: "./paths/assets.yml"
  /liabilities: 
    $ref: "./paths/liabilities.yml"
  /houses: 
    $ref: "./paths/houses.yml"
  /children: 
    $ref: "./paths/children.yml"
  /risks: 
    $ref: "./paths/risks.yml"
  /plots: 
    $ref: "./paths/plots.yml"
components:
  schemas:
    # Source: https://github.com/designapis/openapi/blob/main/ch20/openapi.yml
    Account:
      $ref: "./schemas/resources.yml#/Account"
    Session:
      type: object
      properties:
        access_token:
          type: string
          description: "JWT access token with short expiration"
        refresh_token:
          type: string
          description: "Refresh token to obtain a new access token when expired"
        expires_in:
          type: integer
          description: "Access token expiration time in seconds"
          example: 3600
    OASError: 
      type: object
      properties:
        message:
          type: string
          description: Human-readable error message
        errors:
          type: array
          items:
            type: object
            properties:
              path:
                type: string
                description: For input validation errors, identifies where in the JSON request body the error occured
              message:
                type: string
                description: Human-readable error message
              errorCode:
                type: string
                description: Code indicating error type
    Problem: 
      type: object
      properties:
        type:
          type: string
          description: URI indicating error type
        title:
          type: string
          description: Human-readable error title
        status:
          type: integer
          description: HTTP status code
        detail:
          type: string
          description: Human-readable error details
        instance:
          type: string
          description: URI indicating error instance
  securitySchemes:
    apiKey:
      description: API key for API User Authentication
      type: apiKey
      name: api-key
      in: header
    accessToken:
      description: Bearer token for accessing private resource
      type: http
      scheme: bearer
      bearerFormat: JWT
    refreshToken:
      description: Bearer token for refreshing access token
      type: http
      scheme: bearer
      bearerFormat: JWT